ARG PHP_MAJOR_VERSION=8.3
FROM wordpress:php${PHP_MAJOR_VERSION}
ARG PHP_MAJOR_VERSION

# Install apt dependencies
RUN set -ex; \
    apt-get update && apt-get install -qq -y --fix-missing --no-install-recommends \
        mariadb-client \
        mariadb-server \
        curl; \
    apt-get clean; \
    rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/* /srv/provision/;

# Install node and npm for dev assets
RUN curl -fsSL https://deb.nodesource.com/setup_23.x | bash - && \
    apt-get install -y nodejs \
    build-essential && \
    node --version && \ 
    npm --version

# Install and enable xdebug
RUN set -ex; \
    pecl install xdebug; \
    docker-php-ext-enable xdebug;

# Install test harness
COPY wordpress_version.txt /
RUN set -ex; \
    curl "https://codeload.github.com/WordPress/wordpress-develop/tar.gz/$(cat /wordpress_version.txt)" -o "/wordpress.tar.gz"; \
    mkdir /wordpress; \
    tar -xf /wordpress.tar.gz -C /wordpress --strip-components=1; \
    rm /wordpress.tar.gz;

RUN cd /wordpress; \
    npm i; \
    npm run build:dev;

# Env vars
ENV WORDPRESS_DB_NAME wordpress
ENV WORDPRESS_DB_USER wordpress
ENV WORDPRESS_DB_PASS password
ENV WORDPRESS_DB_HOST 127.0.0.1
ENV XDEBUG_MODE coverage

# Configure test harness
COPY ./bin/configure-test-harness.sh /usr/local/bin/
RUN configure-test-harness.sh

# Setup entrypoint
COPY ./bin/entrypoint.sh /usr/local/bin/
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

WORKDIR /workspace