<?php
/**
 * Generates an array of country codes and their respective continents
 *
 */

function geoip_country_list() {

	$countries = array(
		"AF" => array("country" => "Afghanistan", "continent" => "AS"),
		"AX" => array("country" => "Åland Islands", "continent" => "EU"),
		"AL" => array("country" => "Albania", "continent" => "EU"),
		"DZ" => array("country" => "Algeria", "continent" => "AF"),
		"AS" => array("country" => "American Samoa", "continent" => "OC"),
		"AD" => array("country" => "Andorra", "continent" => "EU"),
		"AO" => array("country" => "Angola", "continent" => "AF"),
		"AI" => array("country" => "Anguilla", "continent" => "NA"),
		"AQ" => array("country" => "AN", "continent" => "AN"),
		"AG" => array("country" => "Antigua and Barbuda", "continent" => "NA"),
		"AR" => array("country" => "Argentina", "continent" => "SA"),
		"AM" => array("country" => "Armenia", "continent" => "AS"),
		"AW" => array("country" => "Aruba", "continent" => "NA"),
		"AU" => array("country" => "Australia", "continent" => "OC"),
		"AT" => array("country" => "Austria", "continent" => "EU"),
		"AZ" => array("country" => "Azerbaijan", "continent" => "AS"),
		"BS" => array("country" => "Bahamas", "continent" => "NA"),
		"BH" => array("country" => "Bahrain", "continent" => "AS"),
		"BD" => array("country" => "Bangladesh", "continent" => "AS"),
		"BB" => array("country" => "Barbados", "continent" => "NA"),
		"BY" => array("country" => "Belarus", "continent" => "EU"),
		"BE" => array("country" => "Belgium", "continent" => "EU"),
		"BZ" => array("country" => "Belize", "continent" => "NA"),
		"BJ" => array("country" => "Benin", "continent" => "AF"),
		"BM" => array("country" => "Bermuda", "continent" => "NA"),
		"BT" => array("country" => "Bhutan", "continent" => "AS"),
		"BO" => array("country" => "Bolivia", "continent" => "SA"),
		"BA" => array("country" => "Bosnia and Herzegovina", "continent" => "EU"),
		"BW" => array("country" => "Botswana", "continent" => "AF"),
		"BV" => array("country" => "Bouvet Island", "continent" => "AN"),
		"BR" => array("country" => "Brazil", "continent" => "SA"),
		"IO" => array("country" => "British Indian Ocean Territory", "continent" => "AS"),
		"BN" => array("country" => "Brunei Darussalam", "continent" => "AS"),
		"BG" => array("country" => "Bulgaria", "continent" => "EU"),
		"BF" => array("country" => "Burkina Faso", "continent" => "AF"),
		"BI" => array("country" => "Burundi", "continent" => "AF"),
		"KH" => array("country" => "Cambodia", "continent" => "AS"),
		"CM" => array("country" => "Cameroon", "continent" => "AF"),
		"CA" => array("country" => "Canada", "continent" => "NA"),
		"CV" => array("country" => "Cape Verde", "continent" => "AF"),
		"KY" => array("country" => "Cayman Islands", "continent" => "NA"),
		"CF" => array("country" => "Central African Republic", "continent" => "AF"),
		"TD" => array("country" => "Chad", "continent" => "AF"),
		"CL" => array("country" => "Chile", "continent" => "SA"),
		"CN" => array("country" => "China", "continent" => "AS"),
		"CX" => array("country" => "Christmas Island", "continent" => "AS"),
		"CC" => array("country" => "Cocos (Keeling) Islands", "continent" => "AS"),
		"CO" => array("country" => "Colombia", "continent" => "SA"),
		"KM" => array("country" => "Comoros", "continent" => "AF"),
		"CG" => array("country" => "Congo", "continent" => "AF"),
		"CD" => array("country" => "The Democratic Republic of The Congo", "continent" => "AF"),
		"CK" => array("country" => "Cook Islands", "continent" => "OC"),
		"CR" => array("country" => "Costa Rica", "continent" => "NA"),
		"CI" => array("country" => "Cote D'ivoire", "continent" => "AF"),
		"HR" => array("country" => "Croatia", "continent" => "EU"),
		"CU" => array("country" => "Cuba", "continent" => "NA"),
		"CY" => array("country" => "Cyprus", "continent" => "AS"),
		"CZ" => array("country" => "Czech Republic", "continent" => "EU"),
		"DK" => array("country" => "Denmark", "continent" => "EU"),
		"DJ" => array("country" => "Djibouti", "continent" => "AF"),
		"DM" => array("country" => "Dominica", "continent" => "NA"),
		"DO" => array("country" => "Dominican Republic", "continent" => "NA"),
		"EC" => array("country" => "Ecuador", "continent" => "SA"),
		"EG" => array("country" => "Egypt", "continent" => "AF"),
		"SV" => array("country" => "El Salvador", "continent" => "NA"),
		"GQ" => array("country" => "Equatorial Guinea", "continent" => "AF"),
		"ER" => array("country" => "Eritrea", "continent" => "AF"),
		"EE" => array("country" => "Estonia", "continent" => "EU"),
		"ET" => array("country" => "Ethiopia", "continent" => "AF"),
		"FK" => array("country" => "Falkland Islands (Malvinas)", "continent" => "SA"),
		"FO" => array("country" => "Faroe Islands", "continent" => "EU"),
		"FJ" => array("country" => "Fiji", "continent" => "OC"),
		"FI" => array("country" => "Finland", "continent" => "EU"),
		"FR" => array("country" => "France", "continent" => "EU"),
		"GF" => array("country" => "French Guiana", "continent" => "SA"),
		"PF" => array("country" => "French Polynesia", "continent" => "OC"),
		"TF" => array("country" => "French Southern Territories", "continent" => "AN"),
		"GA" => array("country" => "Gabon", "continent" => "AF"),
		"GM" => array("country" => "Gambia", "continent" => "AF"),
		"GE" => array("country" => "Georgia", "continent" => "AS"),
		"DE" => array("country" => "Germany", "continent" => "EU"),
		"GH" => array("country" => "Ghana", "continent" => "AF"),
		"GI" => array("country" => "Gibraltar", "continent" => "EU"),
		"GR" => array("country" => "Greece", "continent" => "EU"),
		"GL" => array("country" => "Greenland", "continent" => "NA"),
		"GD" => array("country" => "Grenada", "continent" => "NA"),
		"GP" => array("country" => "Guadeloupe", "continent" => "NA"),
		"GU" => array("country" => "Guam", "continent" => "OC"),
		"GT" => array("country" => "Guatemala", "continent" => "NA"),
		"GG" => array("country" => "Guernsey", "continent" => "EU"),
		"GN" => array("country" => "Guinea", "continent" => "AF"),
		"GW" => array("country" => "Guinea-bissau", "continent" => "AF"),
		"GY" => array("country" => "Guyana", "continent" => "SA"),
		"HT" => array("country" => "Haiti", "continent" => "NA"),
		"HM" => array("country" => "Heard Island and Mcdonald Islands", "continent" => "AN"),
		"VA" => array("country" => "Holy See (Vatican City State)", "continent" => "EU"),
		"HN" => array("country" => "Honduras", "continent" => "NA"),
		"HK" => array("country" => "Hong Kong", "continent" => "AS"),
		"HU" => array("country" => "Hungary", "continent" => "EU"),
		"IS" => array("country" => "Iceland", "continent" => "EU"),
		"IN" => array("country" => "India", "continent" => "AS"),
		"ID" => array("country" => "Indonesia", "continent" => "AS"),
		"IR" => array("country" => "Iran", "continent" => "AS"),
		"IQ" => array("country" => "Iraq", "continent" => "AS"),
		"IE" => array("country" => "Ireland", "continent" => "EU"),
		"IM" => array("country" => "Isle of Man", "continent" => "EU"),
		"IL" => array("country" => "Israel", "continent" => "AS"),
		"IT" => array("country" => "Italy", "continent" => "EU"),
		"JM" => array("country" => "Jamaica", "continent" => "NA"),
		"JP" => array("country" => "Japan", "continent" => "AS"),
		"JE" => array("country" => "Jersey", "continent" => "EU"),
		"JO" => array("country" => "Jordan", "continent" => "AS"),
		"KZ" => array("country" => "Kazakhstan", "continent" => "AS"),
		"KE" => array("country" => "Kenya", "continent" => "AF"),
		"KI" => array("country" => "Kiribati", "continent" => "OC"),
		"KP" => array("country" => "Democratic People's Republic of Korea", "continent" => "AS"),
		"KR" => array("country" => "Republic of Korea", "continent" => "AS"),
		"KW" => array("country" => "Kuwait", "continent" => "AS"),
		"KG" => array("country" => "Kyrgyzstan", "continent" => "AS"),
		"LA" => array("country" => "Lao People's Democratic Republic", "continent" => "AS"),
		"LV" => array("country" => "Latvia", "continent" => "EU"),
		"LB" => array("country" => "Lebanon", "continent" => "AS"),
		"LS" => array("country" => "Lesotho", "continent" => "AF"),
		"LR" => array("country" => "Liberia", "continent" => "AF"),
		"LY" => array("country" => "Libya", "continent" => "AF"),
		"LI" => array("country" => "Liechtenstein", "continent" => "EU"),
		"LT" => array("country" => "Lithuania", "continent" => "EU"),
		"LU" => array("country" => "Luxembourg", "continent" => "EU"),
		"MO" => array("country" => "Macao", "continent" => "AS"),
		"MK" => array("country" => "Macedonia", "continent" => "EU"),
		"MG" => array("country" => "Madagascar", "continent" => "AF"),
		"MW" => array("country" => "Malawi", "continent" => "AF"),
		"MY" => array("country" => "Malaysia", "continent" => "AS"),
		"MV" => array("country" => "Maldives", "continent" => "AS"),
		"ML" => array("country" => "Mali", "continent" => "AF"),
		"MT" => array("country" => "Malta", "continent" => "EU"),
		"MH" => array("country" => "Marshall Islands", "continent" => "OC"),
		"MQ" => array("country" => "Martinique", "continent" => "NA"),
		"MR" => array("country" => "Mauritania", "continent" => "AF"),
		"MU" => array("country" => "Mauritius", "continent" => "AF"),
		"YT" => array("country" => "Mayotte", "continent" => "AF"),
		"MX" => array("country" => "Mexico", "continent" => "NA"),
		"FM" => array("country" => "Micronesia", "continent" => "OC"),
		"MD" => array("country" => "Moldova", "continent" => "EU"),
		"MC" => array("country" => "Monaco", "continent" => "EU"),
		"MN" => array("country" => "Mongolia", "continent" => "AS"),
		"ME" => array("country" => "Montenegro", "continent" => "EU"),
		"MS" => array("country" => "Montserrat", "continent" => "NA"),
		"MA" => array("country" => "Morocco", "continent" => "AF"),
		"MZ" => array("country" => "Mozambique", "continent" => "AF"),
		"MM" => array("country" => "Myanmar", "continent" => "AS"),
		"NA" => array("country" => "Namibia", "continent" => "AF"),
		"NR" => array("country" => "Nauru", "continent" => "OC"),
		"NP" => array("country" => "Nepal", "continent" => "AS"),
		"NL" => array("country" => "Netherlands", "continent" => "EU"),
		"AN" => array("country" => "Netherlands Antilles", "continent" => "NA"),
		"NC" => array("country" => "New Caledonia", "continent" => "OC"),
		"NZ" => array("country" => "New Zealand", "continent" => "OC"),
		"NI" => array("country" => "Nicaragua", "continent" => "NA"),
		"NE" => array("country" => "Niger", "continent" => "AF"),
		"NG" => array("country" => "Nigeria", "continent" => "AF"),
		"NU" => array("country" => "Niue", "continent" => "OC"),
		"NF" => array("country" => "Norfolk Island", "continent" => "OC"),
		"MP" => array("country" => "Northern Mariana Islands", "continent" => "OC"),
		"NO" => array("country" => "Norway", "continent" => "EU"),
		"OM" => array("country" => "Oman", "continent" => "AS"),
		"PK" => array("country" => "Pakistan", "continent" => "AS"),
		"PW" => array("country" => "Palau", "continent" => "OC"),
		"PS" => array("country" => "Palestinia", "continent" => "AS"),
		"PA" => array("country" => "Panama", "continent" => "NA"),
		"PG" => array("country" => "Papua New Guinea", "continent" => "OC"),
		"PY" => array("country" => "Paraguay", "continent" => "SA"),
		"PE" => array("country" => "Peru", "continent" => "SA"),
		"PH" => array("country" => "Philippines", "continent" => "AS"),
		"PN" => array("country" => "Pitcairn", "continent" => "OC"),
		"PL" => array("country" => "Poland", "continent" => "EU"),
		"PT" => array("country" => "Portugal", "continent" => "EU"),
		"PR" => array("country" => "Puerto Rico", "continent" => "NA"),
		"QA" => array("country" => "Qatar", "continent" => "AS"),
		"RE" => array("country" => "Reunion", "continent" => "AF"),
		"RO" => array("country" => "Romania", "continent" => "EU"),
		"RU" => array("country" => "Russian Federation", "continent" => "EU"),
		"RW" => array("country" => "Rwanda", "continent" => "AF"),
		"SH" => array("country" => "Saint Helena", "continent" => "AF"),
		"KN" => array("country" => "Saint Kitts and Nevis", "continent" => "NA"),
		"LC" => array("country" => "Saint Lucia", "continent" => "NA"),
		"PM" => array("country" => "Saint Pierre and Miquelon", "continent" => "NA"),
		"VC" => array("country" => "Saint Vincent and The Grenadines", "continent" => "NA"),
		"WS" => array("country" => "Samoa", "continent" => "OC"),
		"SM" => array("country" => "San Marino", "continent" => "EU"),
		"ST" => array("country" => "Sao Tome and Principe", "continent" => "AF"),
		"SA" => array("country" => "Saudi Arabia", "continent" => "AS"),
		"SN" => array("country" => "Senegal", "continent" => "AF"),
		"RS" => array("country" => "Serbia", "continent" => "EU"),
		"SC" => array("country" => "Seychelles", "continent" => "AF"),
		"SL" => array("country" => "Sierra Leone", "continent" => "AF"),
		"SG" => array("country" => "Singapore", "continent" => "AS"),
		"SK" => array("country" => "Slovakia", "continent" => "EU"),
		"SI" => array("country" => "Slovenia", "continent" => "EU"),
		"SB" => array("country" => "Solomon Islands", "continent" => "OC"),
		"SO" => array("country" => "Somalia", "continent" => "AF"),
		"ZA" => array("country" => "South Africa", "continent" => "AF"),
		"GS" => array("country" => "South Georgia and The South Sandwich Islands", "continent" => "AN"),
		"ES" => array("country" => "Spain", "continent" => "EU"),
		"LK" => array("country" => "Sri Lanka", "continent" => "AS"),
		"SD" => array("country" => "Sudan", "continent" => "AF"),
		"SR" => array("country" => "Suriname", "continent" => "SA"),
		"SJ" => array("country" => "Svalbard and Jan Mayen", "continent" => "EU"),
		"SZ" => array("country" => "Swaziland", "continent" => "AF"),
		"SE" => array("country" => "Sweden", "continent" => "EU"),
		"CH" => array("country" => "Switzerland", "continent" => "EU"),
		"SY" => array("country" => "Syrian Arab Republic", "continent" => "AS"),
		"TW" => array("country" => "Taiwan, Province of China", "continent" => "AS"),
		"TJ" => array("country" => "Tajikistan", "continent" => "AS"),
		"TZ" => array("country" => "Tanzania, United Republic of", "continent" => "AF"),
		"TH" => array("country" => "Thailand", "continent" => "AS"),
		"TL" => array("country" => "Timor-leste", "continent" => "AS"),
		"TG" => array("country" => "Togo", "continent" => "AF"),
		"TK" => array("country" => "Tokelau", "continent" => "OC"),
		"TO" => array("country" => "Tonga", "continent" => "OC"),
		"TT" => array("country" => "Trinidad and Tobago", "continent" => "NA"),
		"TN" => array("country" => "Tunisia", "continent" => "AF"),
		"TR" => array("country" => "Turkey", "continent" => "AS"),
		"TM" => array("country" => "Turkmenistan", "continent" => "AS"),
		"TC" => array("country" => "Turks and Caicos Islands", "continent" => "NA"),
		"TV" => array("country" => "Tuvalu", "continent" => "OC"),
		"UG" => array("country" => "Uganda", "continent" => "AF"),
		"UA" => array("country" => "Ukraine", "continent" => "EU"),
		"AE" => array("country" => "United Arab Emirates", "continent" => "AS"),
		"GB" => array("country" => "United Kingdom", "continent" => "EU"),
		"US" => array("country" => "United States", "continent" => "NA"),
		"UM" => array("country" => "United States Minor Outlying Islands", "continent" => "OC"),
		"UY" => array("country" => "Uruguay", "continent" => "SA"),
		"UZ" => array("country" => "Uzbekistan", "continent" => "AS"),
		"VU" => array("country" => "Vanuatu", "continent" => "OC"),
		"VE" => array("country" => "Venezuela", "continent" => "SA"),
		"VN" => array("country" => "Viet Nam", "continent" => "AS"),
		"VG" => array("country" => "Virgin Islands, British", "continent" => "NA"),
		"VI" => array("country" => "Virgin Islands, U.S.", "continent" => "NA"),
		"WF" => array("country" => "Wallis and Futuna", "continent" => "OC"),
		"EH" => array("country" => "Western Sahara", "continent" => "AF"),
		"YE" => array("country" => "Yemen", "continent" => "AS"),
		"ZM" => array("country" => "Zambia", "continent" => "AF"),
		"ZW" => array("country" => "Zimbabwe", "continent" => "AF")
	);

	return $countries;
}